<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="NetCoreAI" Version="$(NetCoreAIVersion)" />
    <PackageReference Include="NetCoreAI.Backend.Ollama" Version="$(NetCoreAIVersion)" />
    <PackageReference Include="NetCoreAI.Backend.OpenAICompatible" Version="$(NetCoreAIVersion)" />
    <PackageReference Include="NetCoreAI.Backend.Anthropic" Version="$(NetCoreAIVersion)" />
  </ItemGroup>
</Project>
