<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description></Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/NetCoreAI.Core/NetCoreAI.Core.csproj" />
    <ProjectReference Include="../../src/Storage/NetCoreAI.Storage.Sqlite/NetCoreAI.Storage.Sqlite.csproj" />
    <ProjectReference Include="../../src/VectorStores/NetCoreAI.VectorStore.Sqlite/NetCoreAI.VectorStore.Sqlite.csproj" />
    <ProjectReference Include="../NetCoreAI.Conformance/NetCoreAI.Conformance.csproj" />
  </ItemGroup>
</Project>
